# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrowCrawler(object):
    def setupUi(self, CrowCrawler):
        CrowCrawler.setObjectName("CrowCrawler")
        CrowCrawler.resize(638, 356)
        self.centralwidget = QtWidgets.QWidget(CrowCrawler)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(230, 10, 171, 21))
        self.name_label.setObjectName("name_label")
        self.insert_link_label = QtWidgets.QLabel(self.centralwidget)
        self.insert_link_label.setGeometry(QtCore.QRect(20, 70, 91, 18))
        self.insert_link_label.setObjectName("insert_link_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 441, 36))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 130, 103, 36))
        self.pushButton.setObjectName("pushButton")
        CrowCrawler.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CrowCrawler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 28))
        self.menubar.setObjectName("menubar")
        CrowCrawler.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CrowCrawler)
        self.statusbar.setObjectName("statusbar")
        CrowCrawler.setStatusBar(self.statusbar)

        self.retranslateUi(CrowCrawler)
        QtCore.QMetaObject.connectSlotsByName(CrowCrawler)

    def retranslateUi(self, CrowCrawler):
        _translate = QtCore.QCoreApplication.translate
        CrowCrawler.setWindowTitle(_translate("CrowCrawler", "MainWindow"))
        self.name_label.setText(_translate("CrowCrawler", "CrowCrawler Shopspyder"))
        self.insert_link_label.setText(_translate("CrowCrawler", "Insira o link:"))
        self.pushButton.setText(_translate("CrowCrawler", "Inserir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CrowCrawler = QtWidgets.QMainWindow()
    ui = Ui_CrowCrawler()
    ui.setupUi(CrowCrawler)
    CrowCrawler.show()
    sys.exit(app.exec_())
